//
// Created by helen on 10/05/2026.
//

#ifndef SUPERBULLESPROJECT_AURIANNC_HELENAM_ROMAINL_ING1_GR09_CONSTANTES_H
#define SUPERBULLESPROJECT_AURIANNC_HELENAM_ROMAINL_ING1_GR09_CONSTANTES_H

//#define USE_FULLSCREEN 1
#define USE_FULLSCREEN 0
#define APP_SCREEN_W (USE_FULLSCREEN ? 1280 : 800)
#define APP_SCREEN_H (USE_FULLSCREEN ? 800 : 600)
#define APP_CARD (USE_FULLSCREEN ? GFX_AUTODETECT_FULLSCREEN : GFX_AUTODETECT_WINDOWED)
#define ARRAY_COUNT(array)  (sizeof(array)/sizeof(array[0]))
#define NIMAGE 14
#define IMAGESTAT 7
#define FRAME_DURATION 80
#define DELTA_X 14
#define GREEN "\x1b[32m"
#define RESET "\x1b[0m"
#define RED "\033[31m"
#define YELLOW "\033[33m"
#define ORANGE "\033[34m"
#define MAX_PROJECTILES 20
#define VITESSE_TIR 15
#define MAX_BONUS 5
#define DUREE_BONUS 600
#define MAX_BULLES 100
#define GRAVITE 0.30
#define VITESSE_REBOND 7

#endif //SUPERBULLESPROJECT_AURIANNC_HELENAM_ROMAINL_ING1_GR09_CONSTANTES_H
