//
// Created by helen on 10/05/2026.
//

#ifndef SUPERBULLESPROJECT_AURIANNC_HELENAM_ROMAINL_ING1_GR09_JEU_H
#define SUPERBULLESPROJECT_AURIANNC_HELENAM_ROMAINL_ING1_GR09_JEU_H

#include "partie.h"

void jouer(Partie* p, Objet*j);




#endif //SUPERBULLESPROJECT_AURIANNC_HELENAM_ROMAINL_ING1_GR09_JEU_H
